Add gameserver abstraction
gsvgit/PySymGym pull request #49
Opened 2024-04-16 02:58 UTC by Parzival-05

Solving of the issue #4.

Demonstration of the changes made:

1. Running of two learning sessions with two independent servers:
- [instance_manager.log](https://github.com/gsvgit/PySymGym/files/14986237/instance_manager.log) 
- [ml_app.log](https://github.com/gsvgit/PySymGym/files/14986240/ml_app.log) 
- [dataset_for_tests.json](https://github.com/gsvgit/PySymGym/files/14985893/dataset_for_tests.json)
- [dataset_for_tests2.json](https://github.com/gsvgit/PySymGym/files/14985909/dataset_for_tests2.json)
<details>
<summary>Configuration file (Github doesn't allow to upload yaml files):</summary>
  
```YAML
  - ServerName: VSharp
  DatasetConfig:
    dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
    dataset_description: ../workflow/dataset_for_tests.json
  OptunaConfig:
    n_startup_trials: 1
    n_trials: 1
  TrainConfig:
    epochs: 1
- ServerName: VSharp2
  DatasetConfig:
    dataset_base_path: ../maps/DotNet/Maps/Root/bin/Release/net7.0
    dataset_description: ../workflow/dataset_for_tests2.json
  OptunaConfig:
    n_startup_trials: 1
    n_trials: 1
  TrainConfig:
    epochs: 1
  ```

</details>

2. Running two learning sessions with blocking one of them during the validation (with the servername "VSharp"):
- [instance_manager.log](https://github.com/gsvgit/PySymGym/files/14986261/instance_manager.log)
- [ml_app.log](https://github.com/gsvgit/PySymGym/files/14986262/ml_app.log)
- The same datasets
- The same yaml file

I think that to run learning in parallel, more convenient logging is needed (each learning session needs its own stream)

- [ ] Separate logging for each training session

2024-04-16 07:02 UTC, gsvgit reviewed
1. Почему целевая ветка такая странная?
2. Не уверен, что понял, как будут разруливаться всякие вещи типа общей статистики для всех или поиска свободных портов в диапазоне. Предположим, у меня две машины и я хочу 20 инстансов одной и 30 другой. Статистику по обучению хочу собирать общую. Если вдруг порты заняты, то как-то гарантировать, что поиск будет нормально работать и диапазоны не будут страдать от пересечения. Кажется, сейчас на каждый тип машины свой брокер?

2024-04-16 08:37 UTC, emnigma requested changes

2024-04-16 08:37 UTC, emnigma commented on AIAgent/learning/play_game.py
> +        map_steps.append(hetero_input)  # noqa: F821
а что тут `undefined name`?

2024-04-16 08:37 UTC, emnigma commented on AIAgent/run_training.py
> +    return
можно посмотреть в сторону более высокоуровневого апи. например, [ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor)

2024-04-16 08:42 UTC, emnigma commented
В instance-manager после рефактора в
> Running two learning sessions with blocking one of them during the validation (with the servername "VSharp"):

в файле `instance_manager.log` есть ошибка с пустой очередью инстансов. это ожидаемо?

<img width="926" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/fbc655ff-5a99-45c5-841e-97e90081585b">

в этой же секции в `ml_app.log`:

<img width="1015" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/e6172862-e8f5-4197-994c-e14b85d7cb18">

2024-04-16 15:19 UTC, Parzival-05 commented on workflow/config_for_tests.yml
> +- SVMName: VSharp
Про секцию не понял. 

Ввод команды запуска предлагаю в духе питоновских f-strings `launch_cmd`: `dotnet VSharp.ML.GameServer.Runner.dll --mode server --port {port}`, где вместо `{port}` — конкретное значение. Или есть пожелания?

2024-04-16 18:41 UTC, Parzival-05 commented on AIAgent/learning/play_game.py
> +        map_steps.append(hetero_input)  # noqa: F821
Сначала использовал другой линтер, а он ругался на map_steps. Уберу комментарий.

2024-04-17 12:40 UTC, gsvgit commented on workflow/config_for_tests.yml
> +- SVMName: VSharp
Про секцию. Я про то, что параметров для символьных машин в конфге будет много. Можно их сруппирвоать по аналогии с ```DatasetConfig```

2024-04-17 12:41 UTC, gsvgit commented on workflow/config_for_tests.yml
> +- SVMName: VSharp
А почему двух? Это у нас сейчас две машины. а вдруг потом больше будет? Их бы все в конфиг.

2024-04-17 13:13 UTC, emnigma commented on AIAgent/common/utils.py
> +    }
еще актуальней, если ты эту зависимость передаешь в нескольких местах

2024-04-17 13:14 UTC, emnigma commented on AIAgent/launch_servers.py
> +            raise web.HTTPBadRequest(text=sys.exc_info()[1])
давай это тоже залогаем

2024-04-17 13:24 UTC, emnigma commented on AIAgent/run_training.py
> +    return
по дефолту проставляется в конце каждой функции, можно явно не писать)

2024-04-17 19:50 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    with ThreadPoolExecutor() as executor:
Упс. Я об этом даже не подумал. Треды тут ни к месту, ты прав. 

Немного замеров на двух серверах:
Треды:
![image](https://github.com/gsvgit/PySymGym/assets/113194669/a48691f8-5dd6-4c2d-b2e9-1e79c1badff8)

Процессы:
![image](https://github.com/gsvgit/PySymGym/assets/113194669/c6c028ee-deb7-4155-b417-fb39b8c92de5)

2024-04-20 14:26 UTC, Parzival-05 commented on workflow/config_for_tests.yml
> +- SVMName: VSharp
Добавил статистику, пример в описании PR.

2024-04-20 14:28 UTC, Parzival-05 commented on workflow/config_for_tests.yml
> +- SVMName: VSharp
> А почему двух? Это у нас сейчас две машины. а вдруг потом больше будет? Их бы все в конфиг.

Не понял. В конфигфайле должен быть список из конфигураций запускаемых машин, можно запустить любую и в любом количестве.

2024-04-20 14:38 UTC, emnigma commented on AIAgent/epochs_statistics/classes.py
> +    return dict(natsort.natsorted(d.items()))
а зачем?

2024-04-20 14:40 UTC, emnigma commented on AIAgent/epochs_statistics/classes.py
🔥

2024-04-20 14:49 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    with ThreadPoolExecutor() as executor:
Я сделал побольше замеров и оказалось, что разницы в перфомансе почти нет (при запуске двух параллельных сеансов обучения). https://docs.google.com/spreadsheets/d/1xzxpWy0CuYyCrrTGTW9t-oUr0ksTxrKo2VFJMnXQX7E/edit#gid=0
Тут две колонки, одна c обновленной статистикой, другая — без нее. Еще можно подумать над тем, как оптимизировать синхронизацию при сборе статистики. 

Сейчас оставил процессы. Наверное, нужны более содержательные тесты, но мой ноут больше двух параллельных сеансов не потянул...

2024-04-20 15:06 UTC, Parzival-05 commented on AIAgent/launch_servers.py
> +            raise web.HTTPBadRequest(text=sys.exc_info()[1])
Залогал

2024-04-20 15:21 UTC, emnigma requested changes

2024-04-20 15:21 UTC, emnigma commented on AIAgent/launch_servers.py
> +        def start_server() -> tuple[subprocess.Popen[bytes], int, str]:
это точно не нужно блокировать

2024-04-20 15:21 UTC, emnigma commented on AIAgent/launch_servers.py
> +        svms_info_sep.extend(count * [svm_info])
наверное не очень хорошо, что типы инстансов одни и те же, если count == 1 (`SVMInfo`) и если count >= 1 (тоже `SVMInfo`), смысл в них получается разный. Еще не очень хорошо, что они мутабельные

возможно можно аннотировать SVMInfo как `dataclass(frozen=True)`, объявить какой-нибудь `SingleServerSVMInfo`, в котором `count` не будет

это изменение не сильно важно, в принципе можно так оставить

2024-04-20 15:21 UTC, emnigma commented on AIAgent/ml/training/training.py
> +    statistics_collector,  # AutoProxy[StatisticsCollector]
а нельзя тип написать?

2024-04-20 15:21 UTC, emnigma commented on AIAgent/run_training.py
> +        svm_info,
```suggestion
        svm_info=svm_info,
```

2024-04-20 15:21 UTC, emnigma commented on AIAgent/run_training.py
> +                    statistics_collector,
желательно keywords указать, тогда случайно будет труднее передать не тот аргумент. я посмотрел, так можно: https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.Executor.submit

2024-04-20 15:21 UTC, emnigma commented on requirements.txt
> +natsort==8.4.0
нет \n в конце файла

2024-04-20 15:31 UTC, emnigma commented on AIAgent/run_training.py
> +    with ThreadPoolExecutor() as executor:
оч странно! учитывая, что каждый таск должен запускать инференс нейронки, во время которого GIL запрещает вообще чему-либо работать. мб раз запуск на GPU происходит, то вычисление технически IO-операция

кстати, ты на каком количестве шагов запускал? на тестовом(200+) или на боевом(2000+)?

2024-04-20 15:35 UTC, emnigma commented
@Parzival-05  тут launch_command нужна чтобы ее скопировать и воспроизвести. можно ее как-то форматную, чтобы это снова было возможно?

<img width="2492" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/23455ed5-a8ab-4429-afec-e2934446c2be">

2024-04-20 15:58 UTC, Parzival-05 commented on AIAgent/epochs_statistics/classes.py
> +    return dict(natsort.natsorted(d.items()))
Сортировка ключей в естественном порядке, а не лексикографическом

2024-04-20 16:36 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    with ThreadPoolExecutor() as executor:
Запускал на CPU, шагов 200

2024-04-21 07:10 UTC, Parzival-05 commented on AIAgent/launch_servers.py
> +            raise web.HTTPBadRequest(text=f"Parameter {key} is required")
Хммм, у меня не получается воспроизвести снова, хотя я мог. На очевидных конфигах падает c KeyError раньше, не доходя досюда. Уберу.

2024-04-21 07:34 UTC, Parzival-05 commented on AIAgent/ml/training/training.py
> +    statistics_collector,  # AutoProxy[StatisticsCollector]
```python 
print(type(statistics_collector)) ------> <class 'multiprocessing.managers.AutoProxy[StatisticsCollector]'>
```
![image](https://github.com/gsvgit/PySymGym/assets/113194669/4e8ab632-438c-4c2a-907c-a59c8fe510c2)

`AutoProxy` это функция, которая еще и параметризуется типом? Если честно, то не понял, как это работает.

2024-04-21 08:42 UTC, Parzival-05 commented
Все замечания, кажется, исправил. Осталось только сделать черри пик на train refactoring.

2024-04-21 12:58 UTC, emnigma commented on AIAgent/run_training.py
> +    return
@Parzival-05 , убери пож

2024-04-21 13:22 UTC, emnigma commented on AIAgent/ml/training/training.py
> +    statistics_collector,  # AutoProxy[StatisticsCollector]
На 968 строчке имя функции задается в зависимости от передаваемого типа:
<img width="634" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/8bc22d4b-23eb-4bd5-bab1-71a821ad0441">

Видимо, грамотно будет написать `"AutoProxy[StatisticsCollector]"` в типе, так можно в питоне делать

2024-04-21 13:23 UTC, emnigma approved these changes
lgtm! ждем ребейз

2024-04-29 02:02 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    return
Исправил!

2024-04-29 02:03 UTC, Parzival-05 commented on AIAgent/ml/training/training.py
> +    statistics_collector,  # AutoProxy[StatisticsCollector]
Спасибо, добавил

2024-04-29 06:14 UTC, gsvgit commented
@emnigma А как так вышло, что на реквест в dev CI не запускается?

2024-04-29 06:21 UTC, emnigma commented
> @emnigma А как так вышло, что на реквест в dev CI не запускается?

не похоже, чтобы что-то менялось. думаю, из-за форс-пуша

2024-04-29 06:32 UTC, emnigma commented on AIAgent/ml/training/validation.py
> +    Evaluate model using symbolic execution engine. It runs in parallel.
💯

2024-04-29 06:34 UTC, emnigma commented on workflow/config_for_tests.yml
> +    count: 1
@Parzival-05 @gsvgit а мы не хотим на CI гонять несколько серверов?

2024-04-29 08:44 UTC, gsvgit commented on workflow/config_for_tests.yml
> +    count: 1
@emnigma Думаю, это бдует актуально, ктогда USVM подтянем. А пока у нас один только V#.

2024-04-29 08:49 UTC, gsvgit commented
@emnigma @Parzival-05 А правда ли, что пунткты 2 и 3 из issue решены (про изоляцию отделдьных серверов и инстансов)? Это важная штука. Сейчас, если игра одной карты вдруг упала по каким-либо причинам, всё обучение падает. Это не есть хорошо. В таком случае надо бы просто говорить, что на карте всё по нулям, пстать в логи, что там всё упало, а остальные карты должны нормально играться и обучение должно продолжаться.

2024-04-29 08:56 UTC, gsvgit commented on workflow/config_for_tests.yml
> +    count: 1
Записал это как отдельную таску (#56)

2024-04-29 09:26 UTC, emnigma approved these changes

2024-04-29 09:36 UTC, merged