Train refactoring
gsvgit/PySymGym pull request #51
Opened 2024-04-19 11:24 UTC by Anya497

- Add merge steps function
- Add dataset processing function
- Create two different validation functions
- Add incrementation for client
- Add maps to dataset
- Huge refactoring of everything

2024-04-22 14:09 UTC, emnigma requested changes
Крутой ПР!

2024-04-22 14:09 UTC, emnigma commented on AIAgent/ml/training/dataset.py
> +    """
дулбикат, уже был в data_loader_compact.py

2024-04-22 14:09 UTC, emnigma commented on AIAgent/ml/training/training.py
`AIAgent/ml/training/training.py` -> `AIAgent/ml/training/train.py`? по имени функции

2024-04-22 14:09 UTC, emnigma commented on AIAgent/ml/training/utils.py
> +        return 0
```suggestion
    return 0
```

2024-04-22 14:09 UTC, emnigma commented on AIAgent/ml/training/validation.py
> +        )
для инференса я сделаю отдельный одну функцию, его дубликаты не удаляй)

2024-04-22 14:09 UTC, emnigma commented on AIAgent/pretrain.py
какая функция у этого файла? нужно ли его параметризовать через argparse?

2024-04-22 14:20 UTC, Anya497 commented on .pre-commit-config.yaml
> -        language_version: python3.11
У меня не работает с 3.11

2024-04-22 14:51 UTC, emnigma commented on .pre-commit-config.yaml
> -        language_version: python3.11
а что именно?

2024-04-23 07:07 UTC, Anya497 commented on AIAgent/ml/data_loader_compact.py
> +            )  # without resource manager in order to escape file descriptors leaks
Если коротко, то с контекстным менеджером оно падало из-за утечки дескрипторов, а так нет.

2024-04-23 07:21 UTC, Anya497 commented on AIAgent/ml/data_loader_compact.py
> +    Result: TypeAlias = Result
Ок

2024-04-23 07:22 UTC, Anya497 commented on AIAgent/ml/data_loader_compact.py
> +    StatesProperties: TypeAlias = torch.tensor
Ок

2024-04-23 07:22 UTC, Anya497 commented on AIAgent/ml/training/dataset.py
> +Result: TypeAlias = tuple[CoveragePercent, TestsNumber, ErrorsNumber, StepsNumber]
Ок

2024-04-23 07:24 UTC, Anya497 commented on AIAgent/ml/training/utils.py
> +        return 0
Зачем? Там же все возможные случаи рассматриваются. Думаю, это лишнее

2024-04-23 07:25 UTC, Anya497 commented on AIAgent/ml/training/validation.py
> +        )
Да, я видела. Потом вмержим тогда. Сейчас же они нужны.

2024-04-23 07:27 UTC, Anya497 commented on AIAgent/pretrain.py
Это файлик Екатерины. Он не очень актуален, потому что мы в процессе передачи ей нового датасета с другой структурой. Думаю, она сама его поправит.

2024-04-23 07:33 UTC, Anya497 commented on .pre-commit-config.yaml
> -        language_version: python3.11
Пишет, что нет такого интерпретатора. Я вообще убрала версию, так работает.

2024-04-23 08:00 UTC, Anya497 commented on AIAgent/ml/training/dataset.py
> +            self.__indices = self.test_dataset_indices
С этим надо аккуратнее, потому что _indices есть в родительском классе, и, кажется, означает что-то другое. Поэтому я назвала __indices. А вообще "__" тоже имеет место быть для обозначения суперприватности. Учитывая, что в данном контексте эту переменною лучше не переобозначать, "__" вполне подходит.

2024-04-23 11:40 UTC, Anya497 commented on AIAgent/ml/training/dataset.py
> +        threshold_steps_number: Union[int, None] = None,
Ок

2024-04-23 11:40 UTC, Anya497 commented on AIAgent/ml/training/dataset.py
:)

2024-04-24 08:44 UTC, emnigma commented on .pre-commit-config.yaml
> -        language_version: python3.11
вроде надо указывать 'python3.11', но мне лень проверять. Тем более. что выпилим в пользу ruff позже

2024-04-24 08:49 UTC, emnigma commented on AIAgent/ml/data_loader_compact.py
> +        def get_states_properties(
теперь этот коммент актуален для `AIAgent/ml/training/dataset.py

2024-04-24 15:26 UTC, Anya497 commented on AIAgent/ml/data_loader_compact.py
> +        def get_states_properties(
Это все равно все переписывать надо

2024-04-24 15:27 UTC, Anya497 commented on AIAgent/ml/het_gnn_test_train.py
> +        )
И это тоже скоро станет неактуальным

2024-04-24 15:28 UTC, Anya497 commented on AIAgent/ml/training/dataset.py
> +            return step_ids
ок

2024-04-24 16:00 UTC, emnigma approved these changes

2024-04-24 16:14 UTC, merged