Poetry
gsvgit/PySymGym pull request #62
Opened 2024-05-14 07:24 UTC by Anya497

Add poetry to manage dependencies
- Create pyproject.toml file with project information and main dependencies 
- Rewrite part with installing dependencies in README
- Add poetry to github workflows

2024-05-14 07:42 UTC, gsvgit commented on pyproject.toml
> +license = "MIT"
А тут точно просто название лицензии, а не имя файлика, как в ридми?

2024-05-14 07:42 UTC, gsvgit commented on pyproject.toml
> +black = "^24.4.2"
А в воркфлоу для линтера верчия не отъехала?

2024-05-14 16:25 UTC, emnigma requested changes

2024-05-14 16:25 UTC, emnigma commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
авторы специально пустые? Давай нас впишем

2024-05-14 16:25 UTC, emnigma commented on pyproject.toml
> +pytest = "^8.2.0"
тут и ниже: "^<version>"  в `poetry` означает `>=`. Для конкретных версий можно использовать оператор `==`: https://python-poetry.org/docs/dependency-specification/#exact-requirements

2024-05-14 16:25 UTC, emnigma commented on pyproject.toml
Из [логов CI](https://github.com/gsvgit/PySymGym/actions/runs/9075445482/job/24936057663): 
> If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file. ... In a future version of Poetry this warning will become an error!

Надо установить package-mode в false. Должно быть достаточно

Тут описано, как должно быть, если мы не выпускаем пакет: https://python-poetry.org/docs/basic-usage/#operating-modes

2024-05-14 16:25 UTC, emnigma commented on .github/workflows/build_and_run.yaml
Раз теперь используется Poetry, то кэшить тоже надо ее. Посмотрел, должно работать вот так:
```
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.8"
          cache: 'poetry'
```

https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

и давай еще `setup-python` везде поднимем до `@v5`

2024-05-16 06:37 UTC, Anya497 commented on pyproject.toml
> +license = "MIT"
Наверное, все-таки имя файлика

2024-05-16 06:40 UTC, Anya497 commented on pyproject.toml
> +pytest = "^8.2.0"
Я думаю, лучше оставить так, чтобы по возможности работать с наиболее свежими версиями. Если что-то сильно пойдет не так, тогда прибьем.

2024-05-16 06:41 UTC, Anya497 commented on pyproject.toml
> +authors = ["Your Name <you@example.com>"]
Охохохушки. Это же надо спросить у всех почты...

2024-05-16 06:46 UTC, Anya497 commented on pyproject.toml
Справедливо. Потом можно все в pypi выгрузить когда-нибудь. Только надо, наверное, сначала с версионированием разобраться.

2024-05-16 06:54 UTC, Anya497 commented on .github/workflows/build_and_run.yaml
Ок

2024-05-16 07:12 UTC, Anya497 commented on .github/workflows/build_and_run.yaml
что-то оно не работает с `cache: 'poetry'`

2024-05-16 08:41 UTC, Anya497 commented on .github/workflows/build_and_run.yaml
Оно не работало, потому что не было poetry.lock файла. Я его запушила, но не знаю, насколько это адекватное решение.

2024-05-16 16:06 UTC, emnigma commented on .github/workflows/build_and_run.yaml
🫰

2024-05-20 12:26 UTC, merged