Gameserver update
gsvgit/PySymGym pull request #66
Opened 2024-05-21 04:39 UTC by Parzival-05

1. Убран параллельный запуск, теперь обучение запускается по очереди
2. В TrainingDataset два новых поля — c svm_info и коллектором статистики, для абстрагирования от сервера при обучении
3. [Переименована выходная модель](https://github.com/gsvgit/PySymGym/blob/677c99f6bfbe1f164df3738d77fa2a0b3fd26f6e/AIAgent/run_training.py#L128): добавил имя SVM.

2024-05-21 08:04 UTC, Anya497 requested changes
Сейчас в запуске обучения подразумевается, что всегда будет использоваться символьная машина. Это не так. Важно иметь возможность запускать классическое обучение. 
Информация о символьной машине нужна только в `play_game`. На клиенте она не нужна. 
Кажется, отдельная функция `run_training` лишняя.

2024-05-21 18:29 UTC, emnigma reviewed
тэгни еще раз пожалуйста, когда Анины штуки поправишь

2024-05-21 18:29 UTC, emnigma commented on AIAgent/run_training.py
> +    logfile_name = f"{datetime.fromtimestamp(timestamp)}_Adam_KLDL"
мб `logfile_base_name`?

2024-05-21 18:29 UTC, emnigma commented on AIAgent/run_training.py
> +    logfile_name = f"{datetime.fromtimestamp(timestamp)}_Adam_KLDL"
и можно как-то вытащить optimizer? а то ADAM_KLDL захардкожен, а может уже и не он)

2024-05-21 18:29 UTC, emnigma commented on AIAgent/run_training.py
> +        run_training(
> Тогда не нужна будет отдельная функция run_training

с моей точки зрения, лучше чтобы было отдельно. `main` содержит обработку входных данных, а `run_training` уже принимает обработанные значения и что-то с ними делает. чтобы не перегружать одну часть, предлагаю все оставить так

2024-05-21 18:32 UTC, emnigma commented on AIAgent/ml/training/dataset.py
> +        self.statistics_collector = statistics_collector
@Parzival-05 , когда будешь выносить, подумай пожалуйста сразу о том, как это будет для разных SVM: может, будет достаточно названия платформы (JVM, dotnet)? Или надо будет все-таки указывать именно машину?

2024-05-21 22:54 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    logfile_name = f"{datetime.fromtimestamp(timestamp)}_Adam_KLDL"
Не думаю, что можно, т.к. он связан c optuna.Trial

2024-05-21 23:15 UTC, Parzival-05 commented
> На клиенте она не нужна.

Нужно переписать коллектор статистики, чтобы не приходилось прокидывать инфу о названии SVM. Сейчас пока занес SVM в карту, далее еще валидацию причешу.


> Кажется, отдельная функция `run_training` лишняя.

Сейчас в main происходит лишь чтение конфига, а полезная работа делегируется run training. Мне кажется такое разделение более логичным.

2024-05-22 15:15 UTC, Parzival-05 commented
> 5\. В валидации заменил процесс пул на тред пул, т.к. иначе ошибки не ловятся и падает все обучение.

@emnigma, я попытался с процесс пулом, но при ловле ошибок он зависает. Полагаю, что основным бутылочным горлышком при распараллеливании карт будет общение c сервером, поэтому даже c учетом GIL не должно стать на порядок медленнее.

2024-05-23 08:52 UTC, Anya497 requested changes

2024-05-23 08:52 UTC, Anya497 commented on AIAgent/ml/training/validation.py
> +    with ThreadPool(server_count) as p:
А точно ли `ThreadPool` распараллеливает на процессах, а не на потоках? Нам нужно именно на процессах, так как это CPU-bound задача и в питоне она адекватно параллелится только на них.

2024-05-23 09:35 UTC, Parzival-05 commented on AIAgent/ml/training/validation.py
> +    with ThreadPool(server_count) as p:
Теоретически, вычисления на видеокарте, с точки зрения процессора, -- это IO операции, поэтому здесь GIL не должен замедлять весь процесс. Кроме того, при игре в цикле постоянно происходит общение по сокету, что тоже IO операции, поэтому полагаю, что все должны преуспевать.

По-хорошему бы замеры сделать:)

2024-05-23 10:30 UTC, Anya497 commented on AIAgent/run_training.py
> +    for training_parameters in trainings_parameters["SVMConfigs"]:
Я не очень понимаю, почему у нас несколько раз обучение запускается?

2024-05-23 10:33 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    for training_parameters in trainings_parameters["SVMConfigs"]:
В первом цикле ничего не запускается -- лишь парсится информация о платформах. Можно посмотреть на конфиг файл, чтобы осознать.

2024-05-23 10:46 UTC, gsvgit commented on AIAgent/ml/training/validation.py
> +    with ThreadPool(server_count) as p:
@Parzival-05 вот да. Мы тут за производительность бьёмся. Так что просто так менять - не очень. Нужны замеры в реальном окружении.

2024-05-23 17:15 UTC, emnigma commented
> (https://github.com/gsvgit/PySymGym/files/15417104/ml_app.log) [out.txt]

@Parzival-05 
а можем как-то детектить падение и фэйлить остальной пайплайн? в out.txt вижу, что после ошибки на Trial 0 начинается второй Trial. У [optuna.Study.optimize](https://github.com/gsvgit/PySymGym/blob/714700692f565e757e1a4393c9038b6b996ea74a/AIAgent/run_training.py#L107) есть коллбэк на завершение Trial'ов, на нам можем вызвать `raise`?

<img width="824" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/0b6f5986-6018-47ee-9fc2-23edf33a7347">

@Anya497 , @gsvgit , кстати да, как думаете, что хотим делать, если один Trial упал?

2024-05-23 18:14 UTC, emnigma requested changes
🔥

2024-05-23 18:14 UTC, emnigma commented on AIAgent/run_training.py
> +    except RuntimeError:  # TODO: Replace it with a self-created exception
Видимо, ты хочешь в `play_game_task_exn_catcher` выбрасывать что-нибудь типа
```python
...
except Exception as e:
    raise TrialException(...) from e
```
а тут это ловить?
или там что-то нетривиально?

2024-05-23 18:14 UTC, emnigma commented on AIAgent/run_training.py
> +    for training_parameters in trainings_parameters["SVMConfigs"]:
код для валидации yaml-конфига что-то потихоньку растет и пользоваться им уже скорее всего не очень удобно. предлагаю вынести его в отдельный (дата)класс и валидировать `config` просто загрузкой yaml-строчки. Еще так duck typing подержим

2024-05-23 18:17 UTC, emnigma commented
> Как вариант, можно замерить на "боевой" конфигурации и оставить треды, если из-за них не сильно теряем в перфомансе.

Можно сделать конфигурацию настраиваемой (треды/процессы) и отдать на прод Ане)

2024-05-24 06:34 UTC, Anya497 commented on AIAgent/run_training.py
> +    for training_parameters in trainings_parameters["SVMConfigs"]:
Я про второй, в котором запускается `run_training`.

2024-05-24 08:25 UTC, gsvgit commented on AIAgent/run_training.py
> +    for training_parameters in trainings_parameters["SVMConfigs"]:
@Parzival-05 Да. Вся процедура обучения одна. То есть подгрузили данные о машинах, собрали всё в один датасет (возможно, создание датасета стоит вынести из ```run_training```. Мало ли зачем датасет ещё понадобится), запустили обучение.

2024-05-24 08:35 UTC, Anya497 commented
> > (https://github.com/gsvgit/PySymGym/files/15417104/ml_app.log) [out.txt]
> 
> @Parzival-05 а можем как-то детектить падение и фэйлить остальной пайплайн? в out.txt вижу, что после ошибки на Trial 0 начинается второй Trial. У [optuna.Study.optimize](https://github.com/gsvgit/PySymGym/blob/714700692f565e757e1a4393c9038b6b996ea74a/AIAgent/run_training.py#L107) есть коллбэк на завершение Trial'ов, на нам можем вызвать `raise`?
> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/40598909/333279875-0b6f5986-6018-47ee-9fc2-23edf33a7347.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Mzk2MTQsIm5iZiI6MTcxNjUzOTMxNCwicGF0aCI6Ii80MDU5ODkwOS8zMzMyNzk4NzUtMGI2ZjU5ODYtNjAxOC00N2VlLTlmYzItMjNlZGYzM2E3MzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA4MjgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNjkxMTJkZTQ2ZDY2Nzc1Mzg1OGEzMTBlY2Y0NjY0NzU5YmY4MGE5NjYwMTlmNmQ2YWE1ZTQwMTRiNGU1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O-_09M1YxVpDy-2eyDn5HjKbQNUhojy5-EplR4xZheY">
> 
> @Anya497 , @gsvgit , кстати да, как думаете, что хотим делать, если один Trial упал?

Думаю, можно запускать следующий Trial, но записывать куда-нибудь информацию об ошибке, с которой он упал.

2024-05-28 16:47 UTC, Parzival-05 commented on AIAgent/epochs_statistics.py
> +        self._running = SVM_name
ахах

2024-05-28 17:14 UTC, Parzival-05 commented on AIAgent/run_training.py
> +    except RuntimeError:  # TODO: Replace it with a self-created exception
Хотел сделать кастомные исключения, хотя все же runtimeerror должно быть достаточно

2024-05-29 10:29 UTC, emnigma commented on AIAgent/ml/training/validation.py
> +    with ThreadPool(server_count) as p:
@Parzival-05 произвел замеры, вердикт: оставляем процессы

2024-06-02 10:58 UTC, Parzival-05 commented
Все проблемы выше исправил. Посмотрите, пожалуйста, еще раз.

2024-06-03 10:19 UTC, emnigma requested changes
Мне все нравится, осталось мелочи поправить

2024-06-03 10:19 UTC, emnigma commented on AIAgent/run_training.py
> +        except RuntimeError:
if this is thrown and is caught in library code, then lets name it. now it is unclear, when this error might be thrown

2024-06-03 10:19 UTC, emnigma commented on AIAgent/epochs_statistics.py
> +        self._svm_count: int = svm_count
never used

2024-06-03 10:19 UTC, emnigma commented on AIAgent/run_training.py
> +    svms_count = len(config.SVMConfigs)
never used

2024-06-03 10:19 UTC, emnigma commented on AIAgent/connection/broker_conn/classes.py
> +        return SingleSVMInfo(**self.__dict__)
тут у тебя в результирующем `SingleSVMInfo` в поле `extra` сохранится count. думаю, лучше явно вызвать конструктор

2024-06-03 10:21 UTC, emnigma commented on AIAgent/connection/broker_conn/classes.py
> +        return SingleSVMInfo(**self.__dict__)
ну или что-то такое сделать

<img width="867" alt="image" src="https://github.com/gsvgit/PySymGym/assets/40598909/4f1b5253-c4c3-4c62-8503-18cfa1e5bc5a">

https://docs.pydantic.dev/latest/concepts/models/#creating-models-without-validation

2024-06-03 19:06 UTC, Parzival-05 commented on AIAgent/run_training.py
> +def model_saver(epochs_info: EpochsInfo, svm_name: str, dir: Path, model: object):
Параметры модельки есть в лог файле, где однозначно сопоставляется timestamp директории, в которой хранятся модельки и названия лог файла. Можно брать оттуда.

В твоей функции я не понял, как указать директорию для сохранения и прокинуть доп. инфу (о названии svm, о поколении)👀

2024-06-03 20:06 UTC, Parzival-05 commented on AIAgent/run_training.py
> +        except RuntimeError:
В процессе игры везде прокидывается RunTimeError, там нужно много порефакторить. Наверное, нужно делать это в следующем PR.

2024-06-03 20:07 UTC, Parzival-05 commented on AIAgent/connection/broker_conn/classes.py
> +        return SingleSVMInfo(**self.__dict__)
Использовал датаклассы, а не модели, т.к. они дают и валидацию, и позволяют удобно создавать объекты из словарей и наоборот. (Еще пытался скрестить attrs c моделями, как ты говорил, но ничего не вышло) 

Насчет доп. поля: исправил [здесь](https://github.com/gsvgit/PySymGym/pull/66/commits/e2b151da1573b370a0f4e413b48030ee1b8cac28)

2024-06-03 20:08 UTC, Parzival-05 commented
Поправил мелочи

2024-06-03 20:35 UTC, emnigma approved these changes
💪

2024-06-03 20:35 UTC, emnigma commented on AIAgent/run_training.py
> +def model_saver(epochs_info: EpochsInfo, svm_name: str, dir: Path, model: object):
лан, давай уже вольем. пусть пока будет так

2024-06-03 20:35 UTC, emnigma commented on AIAgent/run_training.py
> +                print(svm_info.create_single_svm_info().__pydantic_config__)
дебажные принты?

2024-06-03 20:39 UTC, Parzival-05 commented on AIAgent/run_training.py
> +                print(svm_info.create_single_svm_info().__pydantic_config__)
oops

2024-06-03 20:43 UTC, emnigma commented on AIAgent/ml/training/validation.py
> +                error = result  # it is not possible to raise an exception here or to terminate pool due to the pool hanging
можно как-нибудь так:
```python
class AggregatedError(Exception):
    def __init__(self, errors):
        self.errors = errors

    def __str__(self):
        return '\n'.join(str(error) for error in self.errors)
```

сохранять массив ошибок и потом куда-нибудь сериализовывать. Я посмотрел, там кажется немного нетривиально в случае, если хочется сохранять traceback. Давай вольем потом, если надо будет

2024-06-04 08:57 UTC, Anya497 requested changes

2024-06-04 08:57 UTC, Anya497 commented on AIAgent/run_training.py
> +        )
Смотри. У нас тут есть цикл по SVM. Мы в каждой итерации добавляем в `GameMap` информацию о символьной машине, на которой данная карта должна играться. Это правильно. Но зачем мы на каждую итерацию создаем новый датасет? В датасете должны быть все карты вне зависимости от SVM. И `study.optimize` тоже нужно запускать один раз (это запуск обучения, который должен быть один и на всех картах сразу). 
Цикл по SVM нам нужен только чтобы добавить информацию о символьных машинах в `GameMap`. Соответственно, он должен закончиться на 120 строчке. При этом `maps` должен представлять собой список абсолютно всех карт со всех SVM.

2024-06-04 09:26 UTC, Anya497 requested changes

2024-06-04 09:40 UTC, Parzival-05 commented on AIAgent/common/classes.py
> +    epochs: int
Потому что хотим пообучаться на SVM определенное количество поколений. Вдруг для одной хотим 1, а для другой -- 10.

2024-06-04 10:04 UTC, Anya497 commented on AIAgent/common/classes.py
> +    epochs: int
Мы не обучаем модели на SVM. С символьными машинами происходит только валидация. 1 эпоха = 1 валидация. То есть за одну эпоху во время валидации должны символьно исполняться все карты, описанные в dataset.json

2024-07-04 07:15 UTC, Anya497 approved these changes

2024-07-04 13:24 UTC, gsvgit approved these changes

2024-07-04 13:28 UTC, emnigma approved these changes

2024-07-04 13:28 UTC, emnigma commented on AIAgent/run_training.py
> +    # svm_configs: list[SVMConfig],
комменты? убрать?

2024-07-04 13:30 UTC, Anya497 commented on AIAgent/run_training.py
> +    # svm_configs: list[SVMConfig],
Ой, пропустила. Да, сейчас уберу

2024-07-04 14:20 UTC, merged